# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8676cc7c32cbc78d5a400a0e4d2bffcc"
name = "catferrals"
handle = "catferrals"
application_url = "http://localhost:54792"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/webhooks/orders/paid"

[app_proxy]
url = "http://localhost:54792/proxy"
subpath = "referrals"
prefix = "apps"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_customers,write_customers,read_orders,write_script_tags,write_themes"

[auth]
redirect_urls = ["http://localhost:54792/auth/callback", "http://localhost:54792/auth/shopify/callback", "http://localhost:54792/api/auth/callback"]

[pos]
embedded = false 
