# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "31d5ba33bfb27246ff44fa1248ac793a"
name = "catferrals"
handle = "catferrals-2"
application_url = "https://proteins-promised-ferrari-threats.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_app_proxy,write_products,write_script_tags,write_themes"

[auth]
redirect_urls = ["https://proteins-promised-ferrari-threats.trycloudflare.com/auth/callback", "https://proteins-promised-ferrari-threats.trycloudflare.com/auth/shopify/callback", "https://proteins-promised-ferrari-threats.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true
